### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by brian8128** [mapillary/inplace_abn#174]
I'm able to install the package ok, and I can initialize the layer, and I can run it on CPU, but it breaks on GPU.  
```
t = torch.rand(size=(1, 2, 4, 4))
abn = InPlaceABN(2)
abn(t) # works

abn.cuda()
abn(t.cuda()) # Causes an error
```
When I type nvidia-smi I get the following versions:  
NVIDIA-SMI 440.44       Driver Version: 440.44       CUDA Version: 10.2

Stack dump:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-af81edfc5c17> in <module>
      1 l.cuda()
----> 2 l(t.cuda())

~/miniconda3/envs/ML/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/miniconda3/envs/ML/lib/python3.6/site-packages/inplace_abn/abn.py in forward(self, x)
    111     def forward(self, x):
    112         x, _, _ = inplace_abn(x, self.weight, self.bias, self.running_mean, self.running_var,
--> 113                               self.training, self.momentum, self.eps, self.activation, self.activation_param)
    114         return x
    115 

~/miniconda3/envs/ML/lib/python3.6/site-packages/inplace_abn/functions.py in inplace_abn(x, weight, bias, running_mean, running_var, training, momentum, eps, activation, activation_param)
    152                 training=True, momentum=0.1, eps=1e-05, activation="leaky_relu", activation_param=0.01):
    153     return InPlaceABN.apply(x, weight, bias, running_mean, running_var,
--> 154                             training, momentum, eps, activation, activation_param, None)
    155 
    156 

~/miniconda3/envs/ML/lib/python3.6/site-packages/inplace_abn/functions.py in forward(ctx, x, weight, bias, running_mean, running_var, training, momentum, eps, activation, activation_param, group)
     83 
     84             # Update running stats
---> 85             count_ = count.to(dtype=var.dtype)
     86             running_mean.mul_((1 - ctx.momentum)).add_(ctx.momentum * mean)
     87             running_var.mul_((1 - ctx.momentum)).add_(ctx.momentum * var * count_ / (count_ - 1))

RuntimeError: CUDA error: invalid device function
```

**Comment by ducksoup** [comment]
@brian8128 This might be due to the CUDA code being compiled for a different GPU architecture than the one you are running it on. Can you please try to re-compile InPlaceABN after setting the environment variable `TORCH_CUDA_ARCH_LIST="<your gpu archs, separated by ;>"`, e.g. to `TORCH_CUDA_ARCH_LIST="6.0"` if you are using a Pascal GPU?

**Comment by brian8128** [comment]
I have a Nvidia Quatro RTX 6000 GPU. How do  I know what the cuda arch should be?

**Comment by brian8128** [comment]
Well, I don't know what the problem was but I recreated my conda environment with the latest versions of everything and now it works so I'm gonna close the issue. Thanks for your help and the cool repo.

**Comment by leoshine** [comment]
fyi

I have the same problem.
It turns out that I have CUDA Version: 10.1, while I'm using cuda toolkit 10.0 to compile.
Changing cuda toolkit to the right version (10.1) helps me resolve the issue.
