### ISSUE TITLE
RuntimeError: CUDA Error encountered in <function CompiledLib.bn_mean_var_cuda at 0x7fd9869af0d0>

### ISSUE THREAD

**Issue by yjl9122** [mapillary/inplace_abn#8]
When I use InplaceABN, i got such error. But i compile it well

**Comment by yjl9122** [comment]
the error comes form: 
     85             var = x.new().resize_as_(running_var)
     86             _check_contiguous(x, mean, var)
---> 87             _check(_ext.bn_mean_var_cuda, x, mean, var)

**Comment by rotabulo** [comment]
@yjl9122 could you please give us details about the GPU you are using?

**Comment by yjl9122** [comment]
@rotabulo i use cuda8.0 cudnn7, gpu is tesla k80

**Comment by rotabulo** [comment]
@yjl9122 thank you. The CUDA kernels are compiled for sm_50, sm_52 and sm_61 by default, so they won't be compatible with Kepler cards like the K80. For Kepler cards you should modify `build.sh` and set
```
CUDA_GENCODE="\
-gencode=arch=compute_35,code=sm_35 \
-gencode=arch=compute_30,code=sm_30"
```

**Comment by yjl9122** [comment]
@rotabulo Thanks， i get it.

**Comment by yjl9122** [comment]
close

**Comment by yjl9122** [comment]
I got another error. when I run it
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

**Comment by rotabulo** [comment]
@yjl9122 please, have a look at https://github.com/mapillary/inplace_abn/issues/6

**Comment by yjl9122** [comment]
@rotabulo Thanks, i get it. I have solved it.

**Comment by yjl9122** [comment]
closed

**Comment by yjl9122** [comment]
Would you release a version,  syncBatchNormalization like nn.batch_norm when we use it.

**Comment by rotabulo** [comment]
@yjl9122 Having an implementation of synchronized BN is beyond the scope of this work, but it's straightforward to derive it from the code we provide.

**Comment by PkuRainBow** [comment]
I am trying to use the inplaceABN within docker on GPU cluster with P100.  i have run the build.sh and build.py successfully but failed. Could you please help me?

```
  File "/gscratch/home/yuyua/deeplab_v3/modules/functions.py", line 16, in _check
    raise RuntimeError("CUDA Error encountered in {}".format(fn))
RuntimeError: CUDA Error encountered in <function CompiledLib.bn_mean_var_cuda at 0x7f56a691bd90>
```

**Comment by rotabulo** [comment]
@PkuRainBow did you set the proper compute capability in `build.sh`. which is 6.0 for the P100 ?
You should set `-gencode=arch=compute_60,code=sm_60`

**Comment by PkuRainBow** [comment]
I use the default settings.

```
CUDA_GENCODE="\
-gencode=arch=compute_61,code=sm_61 \
-gencode=arch=compute_52,code=sm_52 \
-gencode=arch=compute_50,code=sm_50"
```

**Comment by rotabulo** [comment]
Then it's wrong, you need to set the `compute_60` and `sm_60`.

**Comment by PkuRainBow** [comment]
The original three lines should be deleted?

**Comment by rotabulo** [comment]
If you use only P100, you can delete the other ones, but it will work also if you leave them.

**Comment by PkuRainBow** [comment]
I still get the same error.....

```
  File "/gscratch/home/yuyua/deeplab_v3/modules/functions.py", line 183, in forward
    _check(_ext.bn_mean_var_cuda, x, mean, var)
  File "/gscratch/home/yuyua/deeplab_v3/modules/functions.py", line 16, in _check
    raise RuntimeError("CUDA Error encountered in {}".format(fn))
RuntimeError: CUDA Error encountered in <function CompiledLib.bn_mean_var_cuda at 0x7f9c91dc2d90>
```

**Comment by rotabulo** [comment]
Did you rerun:
```
cd modules
sh build.sh
python build.py
```

**Comment by PkuRainBow** [comment]
Yes, I re-run the command.

**Comment by rotabulo** [comment]
@PkuRainBow we need more information about the type of cuda error. You could print the cuda error here (https://github.com/mapillary/inplace_abn/blob/master/modules/src/bn.cu#L247), by adding
```
fprintf( stderr, "%s\n", cudaGetErrorString( err ) );
```

**Comment by PkuRainBow** [comment]
@rotabulo Thanks for your kind help. I have solved the problem by rebuilding it.
